# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zvCgfcpf85KpzS647mpOT7wf4LUVdsw1

1.Import Libraries
"""

import pandas as pd

"""2. Load the Data"""

df = pd.read_excel('/content/Adidas US Sales Datasets.xlsx') # Replace 'your_data.csv' with your file

"""3. Handle Null Values"""

print(df.isnull().sum()) # Shows null counts per column

"""4. Remove Duplicate Rows"""

df = df.drop_duplicates()

print(df.columns)

"""7. Save Cleaned Data"""

df.to_csv('cleaned_data.csv', index=False)